In [6]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC

In [7]:
df = pd.read_csv('train.csv')

In [8]:
df.head() 

PassengerId  Survived Pclass  \
0          1.0       0.0      3   
1          2.0       1.0      1   
2          3.0       1.0      3   
3          4.0       1.0      1   
4          5.0       0.0      3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0    1.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                             Heikkinen, Miss. Laina  female  26.0    0.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                           Allen, Mr. William Henry    male  35.0    0.0   

   Parch            Ticket     Fare Cabin Embarked  
0    0.0         A/5 21171   7.2500   NaN        S  
1    0.0          PC 17599  71.2833   C85        C  
2    0.0  STON/O2. 3101282   7.9250   NaN        S  
3    0.0            113803  53.1000  C123        S  
4    0.0            373450   8.0500   NaN        S

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [10]:
df1 = df[['Pclass','Sex','Age','Fare','Embarked']]

In [11]:
df1.head()

Pclass     Sex   Age     Fare Embarked
0      3    male  22.0   7.2500        S
1      1  female  38.0  71.2833        C
2      3  female  26.0   7.9250        S
3      1  female  35.0  53.1000        S
4      3    male  35.0   8.0500        S

In [12]:
df1.isnull().sum()

Pclass        4
Sex           5
Age         182
Fare          5
Embarked      7
dtype: int64

In [38]:
df1.fillna({'Age':df1.Age.mean(),'Embarked':'S'},inplace=True)

In [35]:
df1.head()

Pclass     Sex   Age     Fare Embarked
0      3    male  22.0   7.2500        S
1      1  female  38.0  71.2833        C
2      3  female  26.0   7.9250        S
3      1  female  35.0  53.1000        S
4      3    male  35.0   8.0500        S

In [36]:
df2 = pd.get_dummies(df1[['Sex','Embarked']])

In [16]:
df2.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0         1           0           0           1
1           1         0           1           0           0
2           1         0           0           0           1
3           1         0           0           0           1
4           0         1           0           0           1

In [17]:
df3 = df1.select_dtypes(exclude=['object'])    #
df3.head()

Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [18]:
final_data = pd.concat((df2,df3),axis=1) 

In [19]:
final_data.head()

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S   Age     Fare
0           0         1           0           0           1  22.0   7.2500
1           1         0           1           0           0  38.0  71.2833
2           1         0           0           0           1  26.0   7.9250
3           1         0           0           0           1  35.0  53.1000
4           0         1           0           0           1  35.0   8.0500

In [20]:
print(df1)

    Pclass     Sex        Age     Fare Embarked
0        3    male  22.000000   7.2500        S
1        1  female  38.000000  71.2833        C
2        3  female  26.000000   7.9250        S
3        1  female  35.000000  53.1000        S
4        3    male  35.000000   8.0500        S
..     ...     ...        ...      ...      ...
891    NaN     NaN  29.699118      NaN        S
892    NaN     NaN  29.699118      NaN        S
893    NaN     NaN  29.699118      NaN        S
894    NaN     NaN  29.699118      NaN        S
895            NaN  29.699118      NaN        S

[896 rows x 5 columns]


In [21]:
X = pd.get_dummies(df1['Sex']).values
print

<function print>

In [22]:
y = pd.get_dummies(df['Survived']).values
print(y)

[[1 0]
 [0 1]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [23]:
from sklearn.model_selection import train_test_split
X_train ,X_test, y_train,y_test = train_test_split(X,y, test_size=0.2)
print(X_train)

[[1 0]
 [0 1]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]


In [24]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train.reshape(-1,1),y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
y_pred = regressor.predict(X_test.reshape(-1,1))
print(y_pred.reshape(-1,1)[:5])
print(y_test.reshape(-1,1)[:5])


[[1]
 [0]
 [1]
 [0]
 [0]]
[[1]
 [0]
 [1]
 [0]
 [1]]


In [26]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test.reshape(-1,1),y_pred.reshape(-1,1))
print(cm)

[[132  48]
 [ 48 132]]


In [27]:
regressor.score(X_test.reshape(-1,1),y_test.reshape(-1,1))

0.7333333333333333